name: box
run-name: ${{ github.actor }} is testing
on: [workflow_dispatch]
jobs:
  box:
    runs-on: ubuntu-latest
    steps:
    - id: box
      uses: gertcuykens/box@main
      with:
        host: 'localhost'
    - run: |
        echo "msg: ${{ steps.box.outputs.msg }}"
