name: production
run-name: ${{github.actor}}
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - run: |
        eval `ssh-agent -s`
        ssh-add - <<< "${{secrets.SSH_PRIVATE_KEY}}"
        ssh-keyscan -H ${{secrets.SSH_HOST}} > ~/.ssh/known_hosts
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} ./action
