name: production
run-name: ${{github.actor}}
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - run: |
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_ed25519
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} date
