name: production
run-name: ${{github.actor}}
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - run: |
        eval `ssh-agent -s`
        ssh-add - <<< "${{secrets.SSH_PRIVATE_KEY}}"
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} date
