name: test
run-name: ${{ github.actor }} is testing
on:
  workflow_dispatch:
    inputs:
      server:
        description: 'server'
        type: environment
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - env:
        SERVER: ${{ inputs.server }}
      run: |
        echo "server: $SERVER"
