name: test
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      host:
        description: 'SSH environment'
        type: environment
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - run: |
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_ed25519
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} date
